#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed May  4 11:01:12 2022
@author: khaled Darwish
"""
import winding2 as win
import observation2
from observation2 import NOAAreport as noaa

'''
^^^^^^^^^^
* Inputs *
^^^^^^^^^^
'''
activeRegion = 7115
filenumber = 100
dt = 720

path_= '/media/khd2/Spare-Data-Disk/ARTop_winding/Data'

'''
<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
Create a map
<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
'''
Map =win.mapping(activeRegion,path_)

bz = Map.read_data('bz', filenumber)
Map.plotmap(bz,title=r'$B_z$')

## Creat gif file
##---------------

im_st_No = 100
im_ed_No = 103
variable_name = 'bz'  

X=Map.plot_gif(im_st_No, im_ed_No, variable_name, title = 'bz')
'''
<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
Create time series
<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
'''

TS = win.timeseries(activeRegion, path_)

L = TS.read_data( 'totWind_Cur_Pot_Vel')
deltaL = TS.read_data('deltaLflux')

intL, time = TS.integrate_accum('totWind_Cur_Pot_Vel',dt)


# scale factors
int_factor = 1.0e5**4                # cm^4
factor = int_factor*720.0            # cm^4 s
intL = intL*int_factor
deltaL = deltaL*factor


mean, mstd = TS.mean_std(intL,n_points = 2,factor = 3)


overplot_variables = [intL,mean,mstd]
colour = ['c-','r-','b:']
label = ['$\dot{\delta L}$', '$\mu(\dot{\delta L})$', '$\mu+3\sigma$']

y_label = r'$winding$'+' '+ '$(km^4)$'
title = 'test'
X=TS.plot(time, overplot_variables, colour,label,y_label, 'test',unit='h')


'''
<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
Plot X-ray flux
<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
'''

# path1 = '/home/khd2/'                                         # insert the path if you want to download Goes files.
start_time = '2017-08-28 09:00:00'
end_time = '2017-09-04 19:00:00'


X=observation3.goes_xray(start_time, end_time,SatelliteNumber = 15)     # select the time limits and goes satellite number

picked_time, fluxA, fluxb = X.get_data()                        #  get the data

X.plot_xray(picked_time, fluxA, fluxb)                          # plot_xray( time , fluxA , fluxb )  
 
pt, pv = X.xray_peaks(fluxb,'C')                                # xray_peaks(  wavelength  , x-ray class  ) 


## over plot xray with the time series
##------------------------------------
y_label = r'$winding$'+' '+ '$(km^4)$'
title = 'test'
TS.plot(time, overplot_variables, colour,label,y_label, title ,unit='h',oplot=pt)

'''
<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
Plot SDO map
<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
'''

location = 'S08E23'
start = '2017-09-02 00:00:00'
end = '2017-09-02 00:05:00'

Ob = observation3.SDO(start, end, location)
Ob.get_map(graphs=['1600', '171','hmi'])
Ob.plot()
required_levels = [20, 100, 140, 300, 500]
#Ob.plot(field_strength_spots = '1600', level=required_levels)

'''
<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
Plot NOAA 
<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
'''
start = '2017-08-28 00:00:00'
end = '2017-09-04 00:05:00'


report = noaa(start,end)
showAll = report.show()                                                      

variable = 'XRA'                                                             
activeregion = 'AR12672'                                                 # choose the desired active region number.
tr = 'Begin'                                                             # choose the interested time of the event: Begin, Max, End

fltr_events = report.Filter(activeregion, variable)                      # show a list for the selected type/variable in the report such as XRA, FLA etc.                          

XRs = report.toseconds(activeregion, 'XRA', tr)                          # convert the time of the xray to seconds. XRA = X-ray, FLA = flare
Fls = report.toseconds(activeregion, 'FLA', tr)            
combine = report.combine([X2,X3])                                        # combine xray and flare data in one list with time sequence.


# overplot with the integrated timeseries above
overplot_variables = [intL,mean,mstd]
colour = ['c-','r-','b:']
label = ['$\dot{\delta L}$', '$\mu(\dot{\delta L})$', '$\mu+3\sigma$']

y_label = r'$winding$'+' '+ '$(km^4)$'
title = 'test'
TS.plot(time, overplot_variables, colour,label,y_label, title ,unit='h',oplot=combine)

