#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed May  4 11:01:12 2022
@author: khaled Darwish
"""
import winding2 as win
import observation3
from observation3 import NOAAreport as noaa

'''
^^^^^^^^^^
* Inputs *
^^^^^^^^^^
'''
activeRegion = 956
filenumber = 100
dt = 720

path_= '/media/khd2/Spare-Data-Disk/ARTop_winding/Data'

'''
<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
Create a map
<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
'''
Map =win.mapping(activeRegion,path_)

bz = Map.read_data('bz', filenumber)
Map.plotmap(bz,title=r'$B_z$')

## Creat gif file
##---------------

im_st_No = 90
im_ed_No = 104
variable_name = 'bz'  

#X=Map.plot_gif(im_st_No, im_ed_No, variable_name, title = 'bz')
'''
<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
Create time series
<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
'''
start_time = '2011-10-11 20:00:00'
end_time = '2011-10-12 20:00:00'

TS = win.timeseries(activeRegion, path_)

L = TS.read_data( 'totWind_Cur_Pot_Vel')
deltaL = TS.read_data('deltaLflux')

intL, time = TS.integrate_accum(start_time, end_time,'totWind_Cur_Pot_Vel',dt)


# scale factors
int_factor = 1.0e5**4                # cm^4
factor = int_factor*720.0            # cm^4 s
intL = intL*int_factor
deltaL = deltaL*factor


mean, mstd = TS.mean_std(intL,n_points = 2,factor = 3)


overplot_variables = [intL,mean,mstd]
colour = ['c-','r-','b:']
label = ['$\dot{\delta L}$', '$\mu(\dot{\delta L})$', '$\mu+3\sigma$']

y_label = r'$winding$'+' '+ '$(km^4)$'
title = 'test'
X=TS.plot(time, overplot_variables, colour,label,y_label, 'test',unit='h')


'''
<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
Plot X-ray flux
<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
'''

# path1 = '/home/khd2/'                                         # insert the path if you want to download Goes files.
start_time = '2011-10-13 20:00:00'
end_time = '2011-10-14 20:00:00'


X=observation3.goes_xray(start_time, end_time,SatelliteNumber = 15)     # select the time limits and goes satellite number

picked_time, fluxA, fluxb = X.get_data()                        #  get the data

#X.plot_xray(picked_time, fluxA, fluxb)                          # plot_xray( time , fluxA , fluxb )  
 
pt, pv = X.xray_peaks(fluxb,'C')                                # xray_peaks(  wavelength  , x-ray class  ) 


## over plot xray with the time series
##------------------------------------
y_label = r'$winding$'+' '+ '$(km^4)$'
title = 'test'
TS.plot(time, overplot_variables, colour,label,y_label, title ,unit='h',oplot=pt)

'''
<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
Plot SDO map
<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
'''

location = 'S08E23'
start_time = '2011-10-13 20:00:00'
end_time = '2011-10-13 20:05:00'

#Ob = observation3.SDO(start_time, end_time, location)
#Ob.get_map(graphs=['1600', '171','hmi'])
#Ob.plot()
required_levels = [20, 100, 140, 300, 500]
#Ob.plot(field_strength_spots = '1600', level=required_levels)

'''
<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
Plot NOAA 
<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
'''
start_time = '2011-10-13 20:00:00'
end_time = '2011-10-14 20:00:00'

variable = 'FLA'
activeregion = 'AR11316'
tr = 'Begin'

report = noaa(start_time,end_time)
showAll = report.show()

fltr_events = report.Filter(activeregion, variable)
XRs = report.toseconds(activeregion, 'XRA', tr)  
Fls = report.toseconds(activeregion, 'FLA', tr)            
combine = report.combine([XRs,Fls])    


overplot_variables = [intL,mean,mstd]
colour = ['c-','r-','b:']
label = ['$\dot{\delta L}$', '$\mu(\dot{\delta L})$', '$\mu+3\sigma$']

y_label = r'$winding$'+' '+ '$(km^4)$'
title = 'test'
TS.plot(time, overplot_variables, colour,label,y_label, title ,unit='h',oplot=combine)
